
name: Full testing

on:
  push:
    branches:
      - fullTest

jobs:
  test_all:
    name: Test on ${{ matrix.os }} with Node version ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ 8.x, 10.x, 12.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm test
