
name: Full testing

on:
  push:
    branches:
      - fullTest

jobs:
  test_all:
    name: Node ${{ matrix.node_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ 4.x, 5.x 6.x, 7.x, 8.x, 9.x, 10.x, 11.x 12.x ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: |
          npm install
          npm test
