
name: Simple test on push

on: 
  push:
    branches-ignore:
      - master

jobs:
  test_simple:
    name: Simple test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          npm install
          npm test